# Name of workflow
name: CI

# Trigger on which the code will be run
on: 
  push: 
    branches: main
  pull_request: 

# Jobs which can be run in parallel
jobs:
  linting:
    # Name of job is linting
    # Where this job will be run 
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['3.9', '3.10']

    # Steps to run that job
    steps:
      # Assigning name and using predefined actions for steps
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      
      - name: Run flake8
        run: |
          flake8 main.py

  testing: 
    needs: linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['3.9', '3.10']

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      # - name: Install unittest
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install unittest

      - name: Run tests
        run: |
          python test.py

      - name: Create CML report
        uses: iterative/setup-cml@v2
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          echo "# First Line of our report" >> report.md
          echo "## Bar Plots" >> report.md
          # echo '![](./bars.png "Bar plot")' >> report.md
          echo "## Line Plots" >> report.md
          # echo '![](./lines.png "Bar plot")' >> report.md

          cml comment create report.md
