# Name of workflow
name: CI

# Trigger on which the code will be run
on: push

# Jobs which can be run in parallel
jobs:
  linting:
    # Name of job is linting
    # Where this job will be run 
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    # Steps to run that job
    steps:
      # Assigning name and using predefined actions for steps
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      
      - name: Run flake8
        run: |
          flake8 main.py
